name: Playwright Java Tests
on:
  workflow_dispatch:
    inputs:
      headlessOption:
        description: "Run test with headless option"
        required: true
        default: "yes"
        type: choice
        options:
          - yes
          - no
      browserOption:
        description: "Run test on below browser"
        required: true
        default: "chrome"
        type: choice
        options:
          - chrome
          - webkit
          - firefox
      suiteFile:
        description: "Select Test Suite Key (e.g., Sanity_Test)"
        required: true
        type: choice
        options:
          - Sanity_Test

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      HEAD_LESS: ${{ github.event.inputs.headlessOption }}
      TEST_BROWSER: ${{ github.event.inputs.browserOption }}
      # We store the input key here
      INPUT_SUITE_KEY: ${{ github.event.inputs.suiteFile }}
      APP_USERNAME: ${{ secrets.APP_USERNAME }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Map Suite File from JSON
        # This step reads your JSON and creates the $XML_SUITE variable and add file name with location below
        run: |
          RESOLVED_FILE=$(jq -r --arg KEY "$INPUT_SUITE_KEY" '.[$KEY]' .github/workflows/vars/test-suites.json)
          echo "XML_SUITE=$RESOLVED_FILE" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Install
        run: mvn -B install -D skipTests --no-transfer-progress

      - name: Install Playwright Browsers
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

      - name: Run Playwright tests
        # Use the single variable $XML_SUITE here
        run: |
          mvn clean test \
          -DsuiteXmlFile="TestSuites/$XML_SUITE" \
          -Dheadless=${HEAD_LESS} \
          -Dbrowser=${TEST_BROWSER} \
          -DuserName=${APP_USERNAME} \
          -DuserPassword=${APP_PASSWORD}

      - name: Upload Test Execution Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: execution-results
          path: |
            reports/
            resultVideos/
            screenshots/
          retention-days: 30